server.port=8085

app.token.secret=${APP_TOKEN_SECRET:marketplace_secret_key_2026}
auth.service.url=http://localhost:8081
product.service.url=http://localhost:8082
order.service.url=http://localhost:8084

spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.security.servlet.UserDetailsServiceAutoConfiguration
