server.port=8080

services.auth.url=http://localhost:8081
services.product.url=http://localhost:8082
services.cart.url=http://localhost:8083
services.order.url=http://localhost:8084
services.admin.url=http://localhost:8085

spring.servlet.multipart.enabled=false
